# MoveIt uses this configuration for controller management

trajectory_execution:
  allowed_execution_duration_scaling: 2.0
  allowed_goal_duration_margin: 0.5
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_controller
    - right_arm_controller
    - left_hand_controller
    - right_hand_controller

  left_arm_controller:
    type: FollowJointTrajectory
    joints:
      - openarm_left_joint1
      - openarm_left_joint2
      - openarm_left_joint3
      - openarm_left_joint4
      - openarm_left_joint5
      - openarm_left_joint6
      - openarm_left_joint7
    action_ns: follow_joint_trajectory
    default: true
  right_arm_controller:
    type: FollowJointTrajectory
    joints:
      - openarm_right_joint1
      - openarm_right_joint2
      - openarm_right_joint3
      - openarm_right_joint4
      - openarm_right_joint5
      - openarm_right_joint6
      - openarm_right_joint7
    action_ns: follow_joint_trajectory
    default: true
  left_hand_controller:
    type: GripperCommand
    joints:
      - openarm_left_finger_joint1
    action_ns: gripper_cmd
    default: true
  right_hand_controller:
    type: GripperCommand
    joints:
      - openarm_right_finger_joint1
    action_ns: gripper_cmd
    default: true